/**
 * Patch notes loader — reads /public/data/patch-notes.json which is
 * regenerated by scripts/fetch-patch-notes.py at build time.
 */

export interface PatchEntry {
  id: string;
  guid: string;
  link: string;
  pubDate: string | null;
  titles:    Partial<Record<'tr' | 'en' | 'de' | 'ru', string>>;
  summaries: Partial<Record<'tr' | 'en' | 'de' | 'ru', string>>;
  bodies:    Partial<Record<'tr' | 'en' | 'de' | 'ru', string>>;
}

export interface PatchPayload {
  fetchedAt: string;
  appId: string;
  count: number;
  entries: PatchEntry[];
}

let cache: Promise<PatchPayload> | null = null;

export function loadPatchNotes(): Promise<PatchPayload> {
  if (!cache) {
    cache = fetch('/data/patch-notes.json')
      .then((r) => {
        if (!r.ok) throw new Error(`patch-notes.json: ${r.status}`);
        return r.json() as Promise<PatchPayload>;
      })
      .catch((err) => {
        cache = null;
        throw err;
      });
  }
  return cache;
}

/** Pick a localised string for the active language, with EN/TR fallback. */
export function pickLocalized(
  bag: Partial<Record<string, string>> | undefined,
  lang: string,
): string {
  if (!bag) return '';
  return (
    bag[lang] ||
    bag.en ||
    bag.tr ||
    Object.values(bag)[0] ||
    ''
  );
}

export function formatPatchDate(iso: string | null, lang: string = 'tr'): string {
  if (!iso) return '';
  try {
    const d = new Date(iso);
    return new Intl.DateTimeFormat(lang, { dateStyle: 'long' }).format(d);
  } catch {
    return iso.slice(0, 10);
  }
}
